### ISSUE TITLE
Craft 4: crashes and other buggy behaviour when trying to configure editor with JSON file

### ISSUE THREAD

**Issue by tremby** [verbb/vizy#116]
**Description**

I am encountering various issues including two different crashes when trying to configure the editor with a JSON file.

**Steps to reproduce**

1. Follow [the documentation to change editor configuration](https://verbb.io/craft-plugins/vizy/docs/get-started/configuration#editor-configuration), adding a json file called `KitchenSink.json` with the contents of the kitchen sink example.

2. In the Craft admin panel, when editing a Vizy field, see KitchenSink appear as an option. Select it and save. After this you can see in the database that the row has been updated with `"vizyConfig": ["KitchenSink.json"]`.

3. Go to edit the field again, see that "Default" is selected, not "KitchenSink". This is bug 1.

4. Save the field again, whether having changed "Default" to "KitchenSink" again or not. See error, presented styled by Craft. (Bug 2 stack trace below).

5. Go to the edit page for an entry which has one of these fields. See another error, this time presented as plain text. (Bug 3 stack trace below).

6. I am then stuck, and my only option as far as I know is to manually change the configuration of the field in the database, to remove the `"vizyConfig"` key from the configuration.

**Additional info**
- Plugin version: craft-4 7e28546166c2181041f9858db69b0525f6400925
- Craft version: 4.0.x-dev 6a88060
- Multi-site: Yes

**Additional context**
- Headless mode
- No problems if I choose "enter a custom config" and paste the same JSON in.

### Bug 2 stack trace

```
Unknown Property – [yii\base\UnknownPropertyException](http://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Setting unknown property: verbb\vizy\fields\VizyField::types

yii\base\UnknownPropertyException: Setting unknown property: verbb\vizy\fields\VizyField::types in /srv/myproject/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /srv/myproject/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('types', Array)
#1 /srv/myproject/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(verbb\vizy\fields\VizyField), Array)
#2 /srv/myproject/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#3 [internal function]: craft\base\Model->__construct(Array)
#4 /srv/myproject/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#5 /srv/myproject/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('verbb\\vizy\\fiel...', Array, Array)
#6 /srv/myproject/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\vizy\\fiel...', Array, Array)
#7 /srv/myproject/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#8 /srv/myproject/vendor/craftcms/cms/src/helpers/Component.php(121): Craft::createObject(Array)
#9 /srv/myproject/vendor/craftcms/cms/src/services/Fields.php(588): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#10 /srv/myproject/vendor/craftcms/cms/src/controllers/FieldsController.php(326): craft\services\Fields->createField(Array)
#11 [internal function]: craft\controllers\FieldsController->actionSaveField()
#12 /srv/myproject/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /srv/myproject/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /srv/myproject/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-field', Array)
#15 /srv/myproject/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('fields/save-fie...', Array)
#16 /srv/myproject/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('fields/save-fie...', Array)
#17 /srv/myproject/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#18 /srv/myproject/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /srv/myproject/web/index.php(12): yii\base\Application->run()
#20 {main}
```

### Bug 3 stack trace

```
An Error occurred while handling another error:
TypeError: verbb\vizy\fields\VizyField::_getConfig(): Argument #2 ($file) must be of type ?string, array given, called in /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php on line 652 and defined in /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php:666
Stack trace:
#0 /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php(652): verbb\vizy\fields\VizyField->_getConfig('vizy', Array)
#1 /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php(175): verbb\vizy\fields\VizyField->_getVizyConfig()
#2 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(257): verbb\vizy\fields\VizyField->getInputHtml(Object(verbb\vizy\models\NodeCollection), Object(craft\elements\Entry))
#3 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(215): craft\fieldlayoutelements\CustomField->inputHtml(Object(craft\elements\Entry), false)
#4 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(210): craft\fieldlayoutelements\BaseField->formHtml(Object(craft\elements\Entry), false)
#5 /srv/myproject/vendor/craftcms/cms/src/web/View.php(1439): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#6 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(211): craft\web\View->namespaceInputs(Object(Closure), 'fields')
#7 /srv/myproject/vendor/craftcms/cms/src/models/FieldLayout.php(681): craft\fieldlayoutelements\CustomField->formHtml(Object(craft\elements\Entry), false)
#8 /srv/myproject/vendor/craftcms/cms/src/web/View.php(1434): craft\models\FieldLayout->craft\models\{closure}()
#9 /srv/myproject/vendor/craftcms/cms/src/models/FieldLayout.php(680): craft\web\View->namespaceInputs(Object(Closure), NULL)
#10 /srv/myproject/vendor/craftcms/cms/src/controllers/ElementsController.php(707): craft\models\FieldLayout->createForm(Object(craft\elements\Entry), false, Array)
#11 /srv/myproject/vendor/craftcms/cms/src/controllers/ElementsController.php(416): craft\controllers\ElementsController->_prepareEditor(Object(craft\elements\Entry), true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
#12 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
#13 /srv/myproject/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(107): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
#14 /srv/myproject/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(48): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#15 /srv/myproject/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#16 /srv/myproject/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#17 /srv/myproject/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#18 /srv/myproject/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send()
#19 /srv/myproject/vendor/craftcms/cms/src/web/ErrorHandler.php(185): yii\web\ErrorHandler->renderException(Object(TypeError))
#20 /srv/myproject/vendor/yiisoft/yii2/base/ErrorHandler.php(135): craft\web\ErrorHandler->renderException(Object(TypeError))
#21 /srv/myproject/vendor/craftcms/cms/src/web/ErrorHandler.php(64): yii\base\ErrorHandler->handleException(Object(TypeError))
#22 [internal function]: craft\web\ErrorHandler->handleException(Object(TypeError))
#23 {main}
Previous exception:
TypeError: verbb\vizy\fields\VizyField::_getConfig(): Argument #2 ($file) must be of type ?string, array given, called in /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php on line 652 and defined in /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php:666
Stack trace:
#0 /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php(652): verbb\vizy\fields\VizyField->_getConfig('vizy', Array)
#1 /srv/myproject/vendor/verbb/vizy/src/fields/VizyField.php(175): verbb\vizy\fields\VizyField->_getVizyConfig()
#2 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(257): verbb\vizy\fields\VizyField->getInputHtml(Object(verbb\vizy\models\NodeCollection), Object(craft\elements\Entry))
#3 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/BaseField.php(215): craft\fieldlayoutelements\CustomField->inputHtml(Object(craft\elements\Entry), false)
#4 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(210): craft\fieldlayoutelements\BaseField->formHtml(Object(craft\elements\Entry), false)
#5 /srv/myproject/vendor/craftcms/cms/src/web/View.php(1439): craft\fieldlayoutelements\CustomField->craft\fieldlayoutelements\{closure}()
#6 /srv/myproject/vendor/craftcms/cms/src/fieldlayoutelements/CustomField.php(211): craft\web\View->namespaceInputs(Object(Closure), 'fields')
#7 /srv/myproject/vendor/craftcms/cms/src/models/FieldLayout.php(681): craft\fieldlayoutelements\CustomField->formHtml(Object(craft\elements\Entry), false)
#8 /srv/myproject/vendor/craftcms/cms/src/web/View.php(1434): craft\models\FieldLayout->craft\models\{closure}()
#9 /srv/myproject/vendor/craftcms/cms/src/models/FieldLayout.php(680): craft\web\View->namespaceInputs(Object(Closure), NULL)
#10 /srv/myproject/vendor/craftcms/cms/src/controllers/ElementsController.php(707): craft\models\FieldLayout->createForm(Object(craft\elements\Entry), false, Array)
#11 /srv/myproject/vendor/craftcms/cms/src/controllers/ElementsController.php(416): craft\controllers\ElementsController->_prepareEditor(Object(craft\elements\Entry), true, Object(craft\web\Response), 'main-form', Object(Closure), Object(Closure), Object(Closure))
#12 [internal function]: craft\controllers\ElementsController->craft\controllers\{closure}(Object(craft\web\Response), 'main-form')
#13 /srv/myproject/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(107): call_user_func(Object(Closure), Object(craft\web\Response), 'main-form')
#14 /srv/myproject/vendor/craftcms/cms/src/web/CpScreenResponseFormatter.php(48): craft\web\CpScreenResponseFormatter->_formatTemplate(Object(craft\web\Response), Object(craft\web\CpScreenResponseBehavior))
#15 /srv/myproject/vendor/yiisoft/yii2/web/Response.php(1095): craft\web\CpScreenResponseFormatter->format(Object(craft\web\Response))
#16 /srv/myproject/vendor/craftcms/cms/src/web/Response.php(275): yii\web\Response->prepare()
#17 /srv/myproject/vendor/yiisoft/yii2/web/Response.php(339): craft\web\Response->prepare()
#18 /srv/myproject/vendor/yiisoft/yii2/base/Application.php(390): yii\web\Response->send()
#19 /srv/myproject/web/index.php(12): yii\base\Application->run()
#20 {main}
```

**Comment by engram-design** [comment]
That should be fixed in the latest `craft-4` branch - and you'll also want to re-save your Vizy fields to ensure it saves an incorrectly-saved setting correctly now.

**Comment by tremby** [comment]
That's fixed these issues for me. Thanks.

**Comment by tremby** [comment]
I think I just got a related crash, given the comment "Temporarily fix a config issue during beta" at the top of the stack trace.

I was adding a new Vizy field. I had an "internal server error" toast pop up when I chose "Vizy" from the list of possible field types. When I clicked to save, I got this error.

```
yii\base\ErrorException: Undefined array key "vizyConfig" in /srv/my-project/vendor/verbb/vizy/src/fields/VizyField.php:86
Stack trace:
#0 /srv/my-project/vendor/craftcms/cms/src/web/ErrorHandler.php(77): yii\base\ErrorHandler->handleError(2, 'Undefined array...', '/srv/my-project...', 86)
#1 /srv/my-project/vendor/verbb/vizy/src/fields/VizyField.php(86): craft\web\ErrorHandler->handleError(2, 'Undefined array...', '/srv/my-project...', 86)
#2 [internal function]: verbb\vizy\fields\VizyField->__construct(Array)
#3 /srv/my-project/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#4 /srv/my-project/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('verbb\\vizy\\fiel...', Array, Array)
#5 /srv/my-project/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('verbb\\vizy\\fiel...', Array, Array)
#6 /srv/my-project/vendor/craftcms/cms/src/Craft.php(53): yii\BaseYii::createObject(Array, Array)
#7 /srv/my-project/vendor/craftcms/cms/src/helpers/Component.php(121): Craft::createObject(Array)
#8 /srv/my-project/vendor/craftcms/cms/src/services/Fields.php(588): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#9 /srv/my-project/vendor/craftcms/cms/src/controllers/FieldsController.php(326): craft\services\Fields->createField(Array)
#10 [internal function]: craft\controllers\FieldsController->actionSaveField()
#11 /srv/my-project/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#12 /srv/my-project/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#13 /srv/my-project/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('save-field', Array)
#14 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('fields/save-fie...', Array)
#15 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('fields/save-fie...', Array)
#16 /srv/my-project/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#17 /srv/my-project/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#18 /srv/my-project/web/index.php(12): yii\base\Application->run()
#19 {main}

```

**Comment by engram-design** [comment]
Fixed properly in the `craft-4` branch now.

**Comment by tremby** [comment]
Thanks!
