### ISSUE TITLE
Cannot add image

### ISSUE THREAD

**Issue by jan-dh** [verbb/vizy#210]
### Describe the bug

When trying to add an image the image selection windows open but I'm unable to actually select an image. Console gives me:

```
caught TypeError: Cannot read properties of undefined (reading 'length')
    at Proxy.<anonymous> (ImageMenuBarItem.vue:187:70)
    at Proxy.<anonymous> (ImageMenuBarItem.vue:221:25)
    at s.constructor.onSelect (AssetSelectorModal.js:205:21)
    at s.constructor.selectElements (BaseElementSelectorModal.js:308:14)
    at s.constructor.<anonymous> (BaseElementSelectorModal.js:429:20)
    at s.constructor.<anonymous> (Base.js:153:23)
    at HTMLDivElement.o (jquery.js?v=1681805548:2:89408)
    at HTMLDivElement.dispatch (jquery.js?v=1681805548:2:43392)
    at w (jquery.mobile-events.js?v=1681805548:2:15447)
    at HTMLDivElement.h (jquery.mobile-events.js?v=1681805548:2:7307)
```

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/5801781/233066951-95d5a417-c365-474a-8a95-7602989dbdee.png">

    
    

### Steps to reproduce

1. Create a vizy field
2. Try to select an image

### Craft CMS version

4.4.7.1

### Plugin version

2.1.1

### Multi-site?

"yes"

**Comment by engram-design** [comment]
Should be fixed in [2.1.2](https://github.com/verbb/vizy/releases/tag/2.1.2)
